// Code generated by MockGen. DO NOT EDIT.
// Source: pr_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	enteties "avito_intern/internal/enteties"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPRService is a mock of PRService interface.
type MockPRService struct {
	ctrl     *gomock.Controller
	recorder *MockPRServiceMockRecorder
}

// MockPRServiceMockRecorder is the mock recorder for MockPRService.
type MockPRServiceMockRecorder struct {
	mock *MockPRService
}

// NewMockPRService creates a new mock instance.
func NewMockPRService(ctrl *gomock.Controller) *MockPRService {
	mock := &MockPRService{ctrl: ctrl}
	mock.recorder = &MockPRServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRService) EXPECT() *MockPRServiceMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRService) CreatePR(ctx context.Context, pr *enteties.CreatePullRequest) (*enteties.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pr)
	ret0, _ := ret[0].(*enteties.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRServiceMockRecorder) CreatePR(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRService)(nil).CreatePR), ctx, pr)
}

// MergePR mocks base method.
func (m *MockPRService) MergePR(ctx context.Context, mergeReq *enteties.MergePullRequest) (*enteties.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, mergeReq)
	ret0, _ := ret[0].(*enteties.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPRServiceMockRecorder) MergePR(ctx, mergeReq interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPRService)(nil).MergePR), ctx, mergeReq)
}

// ReassignPR mocks base method.
func (m *MockPRService) ReassignPR(ctx context.Context, resp *enteties.ReassignPullRequest) (*enteties.ReassignPullRequestResponce, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignPR", ctx, resp)
	ret0, _ := ret[0].(*enteties.ReassignPullRequestResponce)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReassignPR indicates an expected call of ReassignPR.
func (mr *MockPRServiceMockRecorder) ReassignPR(ctx, resp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignPR", reflect.TypeOf((*MockPRService)(nil).ReassignPR), ctx, resp)
}
